conan:
  file_path: conan/conanfile.py
  build_dir: conan/build
targets:
  lib:
    tests: false
    namespace: CT_COMMON_NAMESPACE
    headers:
      base_dir: include/Common
      cmake_variable_file: src/Common/CMakeLists.txt
      cmake_variable_name: LIB_HEADERS_LIST
    sources:
      base_dir: src/Common
      cmake_variable_file: src/Common/CMakeLists.txt
      cmake_variable_name: LIB_SRC_LIST
  lib_units:
    tests: true
    namespace: CT_COMMON_NAMESPACE::tests::unit
    headers:
      base_dir: tests/Common/Unit
      cmake_variable_file: tests/Common/Unit/CMakeLists.txt
      cmake_variable_name: LIB_TESTS_UNIT_HEADERS_LIST
    sources:
      base_dir: tests/Common/Unit
      cmake_variable_file: tests/Common/Unit/CMakeLists.txt
      cmake_variable_name: LIB_TESTS_UNIT_SRC_LIST
  lib_integration:
    tests: true
    namespace: CT_COMMON_NAMESPACE::tests::integration
    headers:
      base_dir: tests/Common/Integration
      cmake_variable_file: tests/Common/Integration/CMakeLists.txt
      cmake_variable_name: LIB_TESTS_INTEGRATION_HEADERS_LIST
    sources:
      base_dir: tests/Common/Integration
      cmake_variable_file: tests/Common/Integration/CMakeLists.txt
      cmake_variable_name: LIB_TESTS_INTEGRATION_SRC_LIST
