SET(LIB_TARGET_NAME Lib)

set(LIB_INCLUDE_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/include")
set(LIB_SRC_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/src")

set(LIB_HEADERS_PREFIX "${LIB_INCLUDE_DIR}/${LIB_TARGET_NAME}/")
set(LIB_SRC_PREFIX "${LIB_SRC_DIR}/${LIB_TARGET_NAME}/")
